version: '3.7'
services:
  mysql:
    image: mysql:8
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE = database
      - MYSQL_USER = admin
      - MYSQL_PASSWORD= password